# System API Endpoints
credit.card.api.host=localhost
credit.card.api.port=8081

global.financial.account.api.host=localhost
global.financial.account.api.port=8081

# Scheduler Configuration
scheduler.frequency=3600000
scheduler.startDelay=60000

# HTTP Configuration
http.port=8082
http.host=0.0.0.0

